configuration: #微信参数配置
  token: fgx_2017
  app-id: wx89fc0d2eadcbb2d7
  app-secret: 436e89c974fe6303ada90e46e3e25ae8
  access-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  upload-temprory-meterial-url: https://api.weixin.qq.com/cgi-bin/media/upload?access_token=ACCESS_TOKEN&type=TYPE
  create-menu-url: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
  jsapi-ticket-url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi
  jsapi-sign-string: jsapi_ticket=TICKET&noncestr=NONCESTR&timestamp=TIMESTAMP&url=URL
  create-qrcode-url: https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token=TOKEN
  create-qrcodeimage-url: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=TICKET
  longlink-to-shortlink-url: https://api.weixin.qq.com/cgi-bin/shorturl?access_token=ACCESS_TOKEN
  get-user-summary-url: https://api.weixin.qq.com/datacube/getusersummary?access_token=ACCESS_TOKEN
  get-user-cumulate-url: https://api.weixin.qq.com/datacube/getusercumulate?access_token=ACCESS_TOKEN
  
logging:
  file: c:/log.txt
  config: classpath:logback-boot.xml
  level: 
    org.apache.log4j.BasicConfigurator: info
    org.springframework.scheduling: info
#    ai.yale.wxserver.web: debug
    ai.yale.wxserver.util: debug
  pattern:
#    console: "%-20(%d{yyyyMMdd_HH:mm:ss.SSS} [%logger][%thread] [%-4relative])  
#                [%X{hostName} %X{requestId} %X{processId} %X{service.timing} ][%level] %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}  
                     -%msg%n"
    file: "%-20(%d{yyyyMMdd_HH:mm:ss.SSS} [%logger{10}][%thread] [%-4relative])  
                [%X{hostName} %X{requestId} %X{processId} %X{service.timing} ][%level] %msg%n"
                